import re


class MTFExpressionParser:
    """
    Parses and translates Multi-Timeframe (MTF) shorthand expressions into
    valid SQL syntax for DuckDB or pandas querying.
    """

    # Mapping of common user aliases to TV intervals (minutes or raw TV string).
    # This ensures that user-friendly timeframes map correctly to the suffixes
    # generated by DataTransformer (e.g. 'RSI_60', 'TREND_240', etc.)
    TIMEFRAME_MAPPING = {
        "1m": "1",
        "3m": "3",
        "5m": "5",
        "15m": "15",
        "30m": "30",
        "45m": "45",
        "1H": "60",
        "1h": "60",
        "2H": "120",
        "2h": "120",
        "3H": "180",
        "3h": "180",
        "4H": "240",
        "4h": "240",
        "1D": "1440",  # The prompt suggested 1440, but D/1D are also valid. We map aliases to their explicit minute/string equivalents.
        "1d": "1440",
        "D": "1440",
        "1W": "1W",
        "1w": "1W",
        "W": "1W",
        "1M": "1M",
        "1m_month": "1M",
        "M": "1M",
    }

    # Matches {TF}:{FACTOR}, e.g., "1H:RSI" or "15m:TREND"
    PATTERN = re.compile(r"\b([A-Za-z0-9]+):([A-Za-z0-9_]+)\b")

    @classmethod
    def _validate_sql_safety(cls, expression: str):
        """
        Check for SQL injection patterns in the expression.
        """
        # Reject expressions containing semicolons, --, /*, or DDL keywords
        # (COPY, INSTALL, LOAD, CALL, CREATE, DROP, ALTER, ATTACH).
        forbidden_patterns = [";", "--", "/*"]
        ddl_keywords = ["COPY", "INSTALL", "LOAD", "CALL", "CREATE", "DROP", "ALTER", "ATTACH"]

        for pattern in forbidden_patterns:
            if pattern in expression:
                raise ValueError(f"SQL injection risk detected: expression contains '{pattern}'")

        # Check for DDL keywords (case-insensitive, whole word)
        for keyword in ddl_keywords:
            pattern = rf"\b{keyword}\b"
            if re.search(pattern, expression, re.IGNORECASE):
                raise ValueError(
                    f"SQL injection risk detected: expression contains DDL keyword '{keyword}'"
                )

    @classmethod
    def parse(cls, expression: str) -> str:
        """
        Translates MTF shorthand in an expression to SQL column names.

        Args:
            expression (str): The shorthand expression (e.g., "1H:TREND > 0")

        Returns:
            str: The translated expression (e.g., "TREND_60 > 0")

        Raises:
            ValueError: If an unrecognized timeframe alias or SQL injection risk is detected.
        """
        cls._validate_sql_safety(expression)

        def replace_match(match):
            tf_alias = match.group(1)
            factor = match.group(2)

            if tf_alias in cls.TIMEFRAME_MAPPING:
                mapped_tf = cls.TIMEFRAME_MAPPING[tf_alias]
            elif tf_alias in cls.TIMEFRAME_MAPPING.values() or tf_alias in ("1D", "D", "1W", "1M"):
                # Allow standard TV intervals to pass through
                mapped_tf = tf_alias
            else:
                # If it consists only of digits, it's a minute interval
                if tf_alias.isdigit():
                    mapped_tf = tf_alias
                else:
                    raise ValueError(f"Unrecognized timeframe alias: '{tf_alias}'")

            return f"{factor}_{mapped_tf}"

        return cls.PATTERN.sub(replace_match, expression)
